---
- hosts: webservers
  remote_user: vagrant
  sudo: yes
  vars:
    ruby_version: '2.1.3'
    ruby_version_with_patch: '2.1.3p242'
    ruby_url: 'ftp://ftp.ruby-lang.org//pub/ruby/2.1/ruby-{{ ruby_version }}.tar.gz'
    redis_bind: 127.0.0.1
  tasks:
    - include: tasks/ruby_from_source.yml
  roles:
    - DavidWittman.redis
